### ISSUE TITLE
worng

### ISSUE THREAD

**Issue by Biyarse** [bdttd000/twitch-account-creator#3]
Proxy error: Could not proxy request /create from localhost:3000 to http://localhost:3001/.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

how could I need set anyting make it work???

**Comment by bdttd000** [comment]
@Biyarse During your attempt, did you set up both client and server services in different terminals? This error occurs when you try to make a client request to a server that is not running.

**Comment by Biyarse** [comment]
thanks it's work..
